### ISSUE TITLE
IDLE error

### ISSUE THREAD

**Issue by vineeth2309** [AndreMiras/pycaw#2] opened 2017-01-07 06:08 UTC
When I use the code to set the system volume, I am getting an IDLE subprocess startup error. The error says IDLE subprocess could not make the connection.

**Comment by AndreMiras** [comment] 2017-01-07 11:30
Could you please give me more information.

- current requirements (pip freeze)
- OS version
- architecture
- Python version
- pycaw version
- project files
- exact stacktrace / accurate error message
- and so on

Otherwise there's no chance I can help you debugging the issue blindly.
Also I've never seen such issue, but Googling it seems it could come from:
a) files in your project
b) admin privilege

See:

- http://stackoverflow.com/questions/29567051/python-error-idles-subprocess-didnt-make-connection-either-idle-cant-start
- http://stackoverflow.com/questions/38987289/idles-subprocess-didnt-make-connection-either-idle-cant-start-a-subprocess-o

**Comment by AndreMiras** [comment] 2017-03-09 02:20
I've installed latest pycaw release (v20160929) and I tried to run [simple_audio_volume_example.py](https://github.com/AndreMiras/pycaw/blob/v20160929/examples/simple_audio_volume_example.py) from IDLE. But it works for me, here is the trace:
```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
====== RESTART: C:/Users/andre/Documents/simple_audio_volume_example.py ======
volume.GetMute(): 0
>>> 
====== RESTART: C:/Users/andre/Documents/simple_audio_volume_example.py ======
volume.GetMute(): 1
>>> 
```

Additional info:
```
(venv) C:\Users\andre\Documents>pip freeze
appdirs==1.4.3
comtypes==1.1.3
enum34==1.1.6
future==0.16.0
packaging==16.8
psutil==5.2.0
pycaw==20160929
pyparsing==2.2.0
six==1.10.0

(venv) C:\Users\andre\Documents>
```


- OS version: Windows 10 professional 64 bits (VirtualBox 5.0.32)
- Python version: 2.7.13 (AMD64) (choco install python2)
- pycaw version: v20160929

I'm closing, but feel free to reopen with additional info so I can reproduce.

**Closed by AndreMiras** 2017-03-09 02:20 UTC
